# Aliases
# alias alias_name="command_to_run"

alias jjj="LeeGee in Brissie"
alias zadd="U7 9 Silva St, Ascot QLD 4007"
alias zemb="leighg@worldsbiggestgaragesale.com.au"
alias zemp="leigh.grigaliunas@gmail.com"
alias zems="leegee27394@gmail.com"
alias zga="git add"
alias zgb="git branch"
alias zgch="git checkout"
alias zgcl="git clone"
alias zgco="git commit -m """
alias zgd="git diff"
alias zgf="git fetch"
alias zgh="git --help"
alias zgi="git init"
alias zgli="git ls-files git ls"
alias zglo="git log"
alias zgm="git merge"
alias zgpl="git pull"
alias zgps="git push"
alias zgrhd="git reset HEAD &lt;file(s)&gt;"
alias zgrhr="git reset --hard"
alias zgrhs="git reset --soft HEAD^"
alias zgsh="git show"
alias zgst="git status"